name: build-every-branch

on:
  push:
    branches:
      - '*'

env:
  DOCKERHUB_USERNAME: aiquant9

# fix error:installation not allowed to Create organization package
permissions:
  packages: write
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >>$GITHUB_OUTPUT
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
        id: branch
      - name: Set image tag
        id: image_tag
        run: echo "new_image_tag=${{ steps.branch.outputs.branch }}-${{ steps.vars.outputs.sha_short }}" >>$GITHUB_OUTPUT
      - id: build-push-image
        uses: iquant9/deploy-action@main
        with:
          registry_username: ${{github.actor}}
          registry_password: ${{secrets.GITHUB_TOKEN}}
          tag: ghcr.io/${{github.actor}}/quant-api:${{ steps.image_tag.outputs.new_image_tag }}
          dockerfile: ./Dockerfile
      - run: echo new image is ${{ steps.build-push-image.outputs.new-image }}
        shell: bash
      - name: Invoke workflow in another repo with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: trigger-set-image.yml
          repo: iquant9/deploy
          inputs: '{ "chart": "quant-api", "image": "${{ secrets.USERNAME }}/quant-api", "sha-tag": "${{ steps.image_tag.outputs.new_image_tag }}" }'
          token: ${{ secrets.WORKFLOW_ACCESS_ALL_MY_REPO }}
